#!/usr/bin/env python3
import glob
import json
import os
import sys


def main():
    if len(sys.argv) < 3:
        print("Usage: generate_gallery.py <registry_dir> <output_file>")
        sys.exit(1)

    registry_dir = sys.argv[1]
    output_file = sys.argv[2]

    examples = []
    for f in glob.glob(os.path.join(registry_dir, "*.json")):
        with open(f) as fp:
            try:
                examples.append(json.load(fp))
            except json.JSONDecodeError:
                pass

    broken = {"showcase": [], "standard": [], "incubator": []}
    warning = {"showcase": [], "standard": [], "incubator": []}
    healthy = {"showcase": [], "standard": [], "incubator": []}

    for ex in examples:
        health = ex.get("ci", {}).get("health", "untested")
        status = ex.get("meta", {}).get("status", "incubator").lower()

        if health == "broken":
            if status in broken:
                broken[status].append(ex)
        elif health == "warning":
            if status in warning:
                warning[status].append(ex)
        elif health == "passing" or health == "healthy":
            if status in healthy:
                healthy[status].append(ex)

    for d in [broken, warning, healthy]:
        for k in d:
            d[k].sort(key=lambda x: x.get("name", "").lower())

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("# Mesa Examples Gallery\n\n")
        f.write("This gallery is automatically generated by the CI system.\n\n")

        # 1. Broken Section (standard + showcase only)
        if broken["standard"] or broken["showcase"]:
            f.write("## 🚨 Broken\n\n")
            if broken["showcase"]:
                f.write("### Showcase\n\n")
                for ex in broken["showcase"]:
                    f.write(f"- **{ex['name']}** (`{ex['id']}`)\n")
                f.write("\n")
            if broken["standard"]:
                f.write("### Standard\n\n")
                for ex in broken["standard"]:
                    f.write(f"- **{ex['name']}** (`{ex['id']}`)\n")
                f.write("\n")

        # 2. Warning Section
        if warning["showcase"] or warning["standard"] or warning["incubator"]:
            f.write("## ⚠️ Warning\n\n")
            if warning["showcase"]:
                f.write("### Showcase\n\n")
                for ex in warning["showcase"]:
                    warn_msg = ex.get("ci", {}).get("warning") or "Unknown warning"
                    f.write(f"- **{ex['name']}** (`{ex['id']}`) - *{warn_msg}*\n")
                f.write("\n")
            if warning["standard"]:
                f.write("### Standard\n\n")
                for ex in warning["standard"]:
                    warn_msg = ex.get("ci", {}).get("warning") or "Unknown warning"
                    f.write(f"- **{ex['name']}** (`{ex['id']}`) - *{warn_msg}*\n")
                f.write("\n")
            if warning["incubator"]:
                f.write("### Incubator\n\n")
                for ex in warning["incubator"]:
                    warn_msg = ex.get("ci", {}).get("warning") or "Unknown warning"
                    f.write(f"- **{ex['name']}** (`{ex['id']}`) - *{warn_msg}*\n")
                f.write("\n")

        # 3. Healthy Section
        if healthy["showcase"] or healthy["standard"] or healthy["incubator"]:
            f.write("## ✅ Healthy\n\n")
            if healthy["showcase"]:
                f.write("### Showcase\n\n")
                for ex in healthy["showcase"]:
                    f.write(f"- **{ex['name']}** (`{ex['id']}`)\n")
                f.write("\n")
            if healthy["standard"]:
                f.write("### Standard\n\n")
                for ex in healthy["standard"]:
                    f.write(f"- **{ex['name']}** (`{ex['id']}`)\n")
                f.write("\n")
            if healthy["incubator"]:
                f.write("### Incubator\n\n")
                for ex in healthy["incubator"]:
                    f.write(f"- **{ex['name']}** (`{ex['id']}`)\n")
                f.write("\n")


if __name__ == "__main__":
    main()
